In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('./trade index.csv')
df[df.keys()[45:-1]]

,2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,98.799352,94.385023,92.545648,91.593165,91.575839,91.177270,90.870502,90.204269,94.296971,93.891415,95.250164,94.793662,93.214952,92.176764,93.146463,95.899293,95.968440,95.844965,95.606750
1,99.744566,108.472284,115.905170,112.320588,117.339196,124.369338,139.521460,140.603338,145.523027,160.564925,167.127250,156.498078,153.287140,146.344341,155.244929,150.745777,152.552950,151.226453,152.161794
2,101.127271,99.663067,105.396893,99.714034,110.661466,111.148547,113.172998,112.164971,128.277064,124.640539,116.841234,113.701696,112.600576,116.102439,122.004113,129.903203,128.922834,132.387662,139.804397
3,105.872434,105.801885,116.048584,130.970237,145.356728,152.364411,174.462906,162.898384,178.726313,200.288582,181.814513,176.811788,164.985296,148.196509,147.998456,172.492887,175.719921,192.990560,194.437529
4,98.974189,97.991835,96.755308,95.044216,93.907062,94.498727,92.000039,93.799984,91.484583,88.729633,87.657653,87.998851,87.871413,88.499226,88.718610,87.387128,86.051903,86.203724,86.656459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,86.080400,100.933235,138.238755,195.524986,247.710470,293.685932,446.608907,272.864977,364.438738,447.023427,455.561574,458.574464,398.959622,218.920734,185.455243,205.007653,217.134663,186.483033,144.188538
117,95.571054,101.024335,103.236547,109.078318,112.756296,115.009276,121.431114,121.019017,126.863686,126.272542,126.006491,125.941965,128.678451,131.452047,136.507361,136.986474,134.848982,138.093187,137.079124
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,107.077793,107.682264,109.324875,110.989193,117.872244,121.534940,124.490888,132.373499,141.236768,146.294834,145.239674,137.508728,135.833052,140.004772,144.852206,151.137534,146.372105,152.145991,165.351304
120,91.949843,95.757996,112.755266,127.280041,200.021865,198.392374,179.185768,160.639000,199.451745,206.161023,190.754443,182.882055,176.725653,169.755997,164.591270,184.198530,175.213088,169.165983,172.400154

In [3]:
label = df.keys()[45:-1]
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
output = imputer.fit_transform(df[label])

In [4]:
df[label] = output

In [5]:
df = df.drop(df.keys()[2:45], axis=1)
df = df.drop(df.keys()[-1], axis=1)
df = df.drop(df.keys()[0], axis=1)

In [6]:
df.to_csv('New_New_trade index.csv')

In [7]:
# 标准化
def standard(datas):
    k = np.power(np.sum(np.power(datas, 2)), 0.5)
    datas = datas / k
    return datas
list = []
for value in df[label].values:
    list.append(standard(value))
df[label] = list

In [8]:
df

,Country Name,2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Albania,0.241709,0.230910,0.226410,0.224080,0.224037,0.223062,0.222312,0.220682,0.230694,0.229702,0.233026,0.231910,0.228047,0.225507,0.227880,0.234614,0.234784,0.234481,0.233899
1,Argentina,0.162525,0.176746,0.188857,0.183016,0.191193,0.202648,0.227337,0.229100,0.237116,0.261626,0.272318,0.254999,0.249767,0.238455,0.252957,0.245626,0.248571,0.246410,0.247934
2,Armenia,0.197802,0.194938,0.206153,0.195038,0.216451,0.217403,0.221363,0.219392,0.250906,0.243793,0.228538,0.222397,0.220244,0.227093,0.238637,0.254087,0.252169,0.258947,0.273453
3,Australia,0.150104,0.150004,0.164532,0.185687,0.206084,0.216020,0.247350,0.230954,0.253395,0.283966,0.257773,0.250681,0.233913,0.210110,0.209830,0.244557,0.249133,0.273619,0.275670
4,Austria,0.249091,0.246618,0.243506,0.239200,0.236338,0.237827,0.231539,0.236069,0.230241,0.223308,0.220610,0.221469,0.221148,0.222728,0.223280,0.219929,0.216569,0.216951,0.218090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"Venezuela, RB",0.067358,0.078980,0.108172,0.152998,0.193834,0.229809,0.349472,0.213517,0.285174,0.349796,0.356477,0.358835,0.312186,0.171306,0.145119,0.160419,0.169908,0.145923,0.112828
117,Vietnam,0.177997,0.188154,0.192274,0.203154,0.210004,0.214200,0.226160,0.225393,0.236278,0.235177,0.234682,0.234562,0.239658,0.244824,0.254239,0.255132,0.251151,0.257193,0.255304
118,Kosovo,0.196522,0.198114,0.203402,0.208411,0.221822,0.226323,0.235460,0.225919,0.241814,0.253389,0.248432,0.243847,0.240053,0.228966,0.228932,0.235122,0.237348,0.236197,0.238092
119,South Africa,0.182523,0.183554,0.186354,0.189191,0.200923,0.207167,0.212206,0.225642,0.240750,0.249372,0.247574,0.234396,0.231539,0.238650,0.246913,0.257627,0.249504,0.259346,0.281856
120,Zambia,0.124434,0.129587,0.152589,0.172245,0.270685,0.268480,0.242488,0.217389,0.269914,0.278993,0.258144,0.247490,0.239159,0.229727,0.222738,0.249272,0.237112,0.228928,0.233305

In [9]:
df.to_csv('New_trade index.csv')