In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('./fiscal balance index.csv')
df.keys()[13:]
df

,Unnamed: 0,Country Name,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,155,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.925556,...,-3.516312,-3.440600,-5.215219,-5.457544,-4.317811,-1.497590,-1.405554,-1.316541,-1.944197,-6.713411
1,0,Argentina,NaN,NaN,NaN,-1.249802,-2.074606,-2.810610,-1.837621,-1.827434,...,-2.745648,-3.018056,-3.253828,-4.252429,-6.000558,-6.654669,-6.693341,-5.441145,-4.395052,-8.588337
2,152,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.874854,-1.493404,-1.592886,-1.942693,-4.836849,-5.632309,-4.785054,-1.751595,-0.977301,-5.402956
3,1,Australia,-2.789943,-4.746345,-4.728944,-3.795118,-2.605177,-1.456791,-0.493282,-0.245967,...,-4.528483,-3.510794,-2.811400,-2.918944,-2.788289,-2.422049,-1.718044,-1.260121,-4.402943,-8.757626
4,2,Austria,-2.945598,-2.136688,-4.541947,-5.013404,-6.140539,-4.357108,-2.371826,-2.668765,...,-2.577134,-2.189054,-1.950078,-2.729142,-1.046242,-1.534591,-0.816119,0.170082,0.609899,-8.045202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,77,"Venezuela, RB",-2.276180,-6.367894,-2.920911,-11.187440,-5.864384,7.939883,2.577188,-4.489350,...,-8.243968,-9.851669,-10.349278,-9.800193,-8.063533,-8.462858,-13.273188,-30.276034,-10.004884,-5.010914
117,107,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.900956,-5.462265,-5.964026,-5.016689,-4.983224,-3.163971,-1.964007,-1.025698,-0.401514,-2.889275
118,191,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.036485,-2.444515,-3.420374,-2.650189,-2.115888,-1.708710,-1.425765,-2.861426,-2.926953,-7.881883
119,94,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.704965,-4.037955,-3.905115,-3.924273,-4.373994,-3.724993,-4.015834,-3.742434,-4.709855,-9.672123
120,109,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.783439,-2.831893,-6.207701,-5.799063,-9.538398,-5.690863,-7.498813,-8.308662,-9.407189,-13.782747

In [3]:
label = df.keys()[13:]
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
output = imputer.fit_transform(df[label])

In [4]:
df[label] = output

In [5]:
df = df.drop(df.keys()[2:13], axis=1)
# df = df.drop(df.keys()[-1], axis=1)
df = df.drop(df.keys()[0], axis=1)

In [6]:
df

,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Albania,-6.211611,-5.006109,-5.162748,-3.457788,-3.263216,-3.179137,-4.884198,-6.586478,-3.520122,-3.516312,-3.440600,-5.215219,-5.457544,-4.317811,-1.497590,-1.405554,-1.316541,-1.944197,-6.713411
1,Argentina,-1.910150,1.500146,3.966895,3.340623,1.650070,0.756974,0.351973,-1.830044,-1.393455,-2.745648,-3.018056,-3.253828,-4.252429,-6.000558,-6.654669,-6.693341,-5.441145,-4.395052,-8.588337
2,Armenia,-6.090177,-3.858527,-2.833846,-2.853563,-1.950397,-2.334231,-1.756524,-7.686465,-4.979425,-2.874854,-1.493404,-1.592886,-1.942693,-4.836849,-5.632309,-4.785054,-1.751595,-0.977301,-5.402956
3,Australia,0.192737,1.051187,1.323849,1.708808,1.773806,1.476039,-1.101341,-4.566680,-5.119826,-4.528483,-3.510794,-2.811400,-2.918944,-2.788289,-2.422049,-1.718044,-1.260121,-4.402943,-8.757626
4,Austria,-1.864522,-1.381754,-4.839052,-2.540769,-2.563441,-1.382364,-1.521402,-5.355725,-4.453404,-2.577134,-2.189054,-1.950078,-2.729142,-1.046242,-1.534591,-0.816119,0.170082,0.609899,-8.045202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"Venezuela, RB",-1.482312,0.171416,2.470453,4.094751,-1.604650,-2.815426,-3.461019,-8.685966,-4.739491,-8.243968,-9.851669,-10.349278,-9.800193,-8.063533,-8.462858,-13.273188,-30.276034,-10.004884,-5.010914
117,Vietnam,-1.854854,-2.558550,-0.149549,-0.953926,0.200580,-1.738695,-0.447187,-4.824295,-2.250906,-0.900956,-5.462265,-5.964026,-5.016689,-4.983224,-3.163971,-1.964007,-1.025698,-0.401514,-2.889275
118,Kosovo,3.394641,1.570294,-4.618970,-2.285694,2.643793,6.682632,0.039073,1.618183,-1.009466,-1.036485,-2.444515,-3.420374,-2.650189,-2.115888,-1.708710,-1.425765,-2.861426,-2.926953,-7.881883
119,South Africa,-0.958147,-1.588173,-1.043937,-0.102913,0.814832,1.218816,-0.485690,-4.668770,-4.520303,-3.704965,-4.037955,-3.905115,-3.924273,-4.373994,-3.724993,-4.015834,-3.742434,-4.709855,-9.672123
120,Zambia,-4.498905,-5.314295,-2.508441,-2.372064,16.912746,-1.036850,-0.667892,-2.057125,-2.432209,-1.783439,-2.831893,-6.207701,-5.799063,-9.538398,-5.690863,-7.498813,-8.308662,-9.407189,-13.782747

In [7]:
# 标准化
def standard(datas):
    k = np.power(np.sum(np.power(datas, 2)), 0.5)
    datas = datas / k
    return datas
list = []
for value in df[label].values:
    list.append(standard(value))
df[label] = list

In [8]:
df

,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Albania,-0.328629,-0.264851,-0.273138,-0.182936,-0.172643,-0.168194,-0.258402,-0.348462,-0.186234,-0.186033,-0.182027,-0.275914,-0.288735,-0.228436,-0.079231,-0.074362,-0.069652,-0.102859,-0.355177
1,Argentina,-0.104425,0.082011,0.216865,0.182627,0.090207,0.041383,0.019242,-0.100046,-0.076178,-0.150101,-0.164993,-0.177883,-0.232475,-0.328043,-0.363802,-0.365916,-0.297460,-0.240272,-0.469513
2,Armenia,-0.356155,-0.225648,-0.165724,-0.166877,-0.114060,-0.136506,-0.102722,-0.449506,-0.291198,-0.168122,-0.087335,-0.093152,-0.113609,-0.282860,-0.329379,-0.279831,-0.102434,-0.057153,-0.315966
3,Australia,0.012908,0.070402,0.088664,0.114446,0.118799,0.098856,-0.073761,-0.305849,-0.342895,-0.303291,-0.235132,-0.188291,-0.195494,-0.186743,-0.162214,-0.115064,-0.084395,-0.294883,-0.586534
4,Austria,-0.136531,-0.101180,-0.354343,-0.186050,-0.187710,-0.101225,-0.111406,-0.392177,-0.326104,-0.188712,-0.160295,-0.142796,-0.199843,-0.076612,-0.112372,-0.059761,0.012454,0.044660,-0.589116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"Venezuela, RB",-0.034294,0.003966,0.057155,0.094733,-0.037124,-0.065136,-0.080072,-0.200952,-0.109649,-0.190726,-0.227921,-0.239433,-0.226730,-0.186552,-0.195790,-0.307079,-0.700444,-0.231466,-0.115929
117,Vietnam,-0.137427,-0.189564,-0.011080,-0.070677,0.014861,-0.128821,-0.033132,-0.357434,-0.166771,-0.066752,-0.404702,-0.441878,-0.371689,-0.369210,-0.234420,-0.145514,-0.075994,-0.029748,-0.214068
118,Kosovo,0.234300,0.108382,-0.318803,-0.157760,0.182476,0.461238,0.002697,0.111688,-0.069674,-0.071539,-0.168721,-0.236076,-0.182917,-0.146039,-0.117936,-0.098407,-0.197497,-0.202019,-0.544011
119,South Africa,-0.056390,-0.093469,-0.061439,-0.006057,0.047955,0.071731,-0.028584,-0.274771,-0.266033,-0.218048,-0.237646,-0.229828,-0.230955,-0.257422,-0.219227,-0.236344,-0.220253,-0.277189,-0.569233
120,Zambia,-0.144558,-0.170758,-0.080601,-0.076219,0.543437,-0.033316,-0.021461,-0.066099,-0.078151,-0.057305,-0.090994,-0.199465,-0.186334,-0.306486,-0.182858,-0.240950,-0.266972,-0.302270,-0.442864

In [9]:
df.to_csv('New_fiscal balance index.csv')