In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('./School enrollment, tertiary (% gross).csv')
df1 = pd.read_excel('../指标总.xlsx')
lists = df1['Country Name'].tolist()
filled_df = pd.DataFrame()
k = []
for list in lists:
    flag = True
    for i in range(0, 266):
        if df.loc[i]['Country Name'] == list:
            flag = False
            filled_df = filled_df.append(df.loc[i])
            break
    if flag:
        print(list)
        tmp = df1[:]
        for i in range(0, 121):
            if tmp.loc[i]['Country Name'] == list:
                k.append(i)
df = filled_df

In [3]:
df = df.drop(df.keys()[1:46], axis=1)
df = df.drop(df.keys()[-1], axis=1)
label = df.keys()[1:]
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
outputs = imputer.fit_transform(df[label].values)
df[label] = outputs

In [5]:
df.to_csv('New_New_School enrollment.csv')

In [13]:
# 标准化
def standard(datas):
    k = np.power(np.sum(np.power(datas, 2)), 0.5)
    datas = datas / k
    return datas

In [14]:
label = df.keys()[1:]
list = []
for value in df[label].values:
    list.append(standard(value))

In [15]:
df[label] = list
df

,Country Name,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
5,Albania,0.039887,0.042218,0.044278,0.053290,0.050696,0.048642,0.052154,0.060546,0.064601,...,0.237798,0.282485,0.308146,0.313622,0.295623,0.278337,0.273538,0.262029,0.284995,0.275626
9,Argentina,0.093747,0.101803,0.098093,0.113916,0.098817,0.126616,0.131680,0.129411,0.125415,...,0.203763,0.206831,0.208908,0.216311,0.224339,0.232916,0.240247,0.244633,0.254907,0.264838
10,Armenia,0.102656,0.112176,0.112111,0.101872,0.084604,0.084418,0.074935,0.100512,0.148527,...,0.235962,0.204199,0.202338,0.208288,0.205809,0.225974,0.231156,0.241415,0.227776,0.224808
13,Australia,0.077236,0.083688,0.086719,0.143212,0.146303,0.154405,0.165238,0.176725,0.134682,...,0.185959,0.185051,0.185689,0.186854,0.259082,0.264226,0.247137,0.235486,0.253275,0.249426
14,Austria,0.089789,0.095743,0.103792,0.109749,0.116635,0.124120,0.131056,0.136787,0.144594,...,0.216630,0.217842,0.219820,0.218449,0.222756,0.230305,0.234726,0.239228,0.238641,0.240671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,"Venezuela, RB",0.088086,0.090759,0.089936,0.129438,0.133779,0.140451,0.146748,0.147660,0.118159,...,0.200529,0.186195,0.190820,0.199889,0.242183,0.216413,0.223042,0.247348,0.257101,0.282603
257,Vietnam,0.026828,0.018357,0.014882,0.018742,0.021231,0.027140,0.039333,0.066646,0.093946,...,0.242184,0.244497,0.244546,0.298166,0.282227,0.277096,0.257352,0.260584,0.278019,0.273652
261,Kosovo,0.096136,0.103246,0.103312,0.107368,0.115059,0.118419,0.128743,0.128716,0.150006,...,0.201441,0.202754,0.210645,0.220833,0.217054,0.231435,0.237179,0.241131,0.251219,0.268332
263,South Africa,0.139157,0.143288,0.145659,0.159677,0.174022,0.091590,0.113550,0.107712,0.130282,...,0.216229,0.211108,0.219785,0.218448,0.245484,0.230679,0.246643,0.262477,0.263190,0.267267
264,Zambia,0.097370,0.058213,0.064131,0.075648,0.091082,0.084366,0.093955,0.085146,0.109070,...,0.197551,0.195047,0.233528,0.239290,0.290327,0.295521,0.290868,0.246867,0.300682,0.303698

In [16]:
df.to_csv('New_School enrollment.csv')