In [15]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [16]:
df = pd.read_csv('../政治/ControlofCorruption.csv')
df1 = pd.read_csv('../经济/New_fiscal balance index.csv')
lists = df1['Country Name'].tolist()
filled_df = pd.DataFrame()
k = []
for list in lists:
    flag = True
    for i in range(0, 214):
        if df.loc[i]['Country Name'] == list:
            flag = False
            filled_df = filled_df.append(df.loc[i])
            break
    if flag:
        print(list)
        tmp = df1[:]
        for i in range(0, 121):
            if tmp.loc[i]['Country Name'] == list:
                k.append(i)
df = filled_df

In [17]:
df

,Unnamed: 0,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
5,6,Albania,-0.845341,-0.853787,-0.723732,-0.813264,-0.790545,-0.706940,-0.605212,-0.545271,...,-0.778729,-0.750956,-0.586141,-0.520960,-0.448980,-0.458257,-0.524145,-0.543374,-0.551931,-0.555924
8,9,Argentina,-0.417056,-0.479977,-0.414410,-0.377738,-0.331239,-0.372122,-0.434875,-0.445475,...,-0.445909,-0.434016,-0.549443,-0.557245,-0.274942,-0.284517,-0.074287,-0.083663,-0.140874,-0.400778
9,10,Armenia,-0.778165,-0.649022,-0.703455,-0.683350,-0.669233,-0.745892,-0.712412,-0.621460,...,-0.588001,-0.530450,-0.565155,-0.584428,-0.637749,-0.614446,-0.385728,-0.203820,0.020228,0.072150
12,13,Australia,1.761436,1.895287,2.005869,1.942668,1.950813,2.000873,2.027343,2.041763,...,1.977507,1.777870,1.849465,1.879955,1.810914,1.790856,1.801111,1.822145,1.662499,1.737494
13,14,Austria,1.915159,1.963869,2.026624,1.912423,1.904877,2.003345,1.828758,1.694034,...,1.427254,1.537241,1.466749,1.508800,1.534535,1.537821,1.601477,1.554295,1.506872,1.271237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,203,"Venezuela, RB",-1.061424,-1.067479,-0.978203,-1.030746,-1.049627,-1.083078,-1.144424,-1.171697,...,-1.258298,-1.306563,-1.394557,-1.389553,-1.350345,-1.369140,-1.494988,-1.512243,-1.558011,-1.605779
204,205,Vietnam,-0.560991,-0.490873,-0.756660,-0.729582,-0.747617,-0.630166,-0.711533,-0.545064,...,-0.532106,-0.482675,-0.438093,-0.429408,-0.457355,-0.599393,-0.488851,-0.524321,-0.351731,-0.285784
117,118,Kosovo,0.360482,-0.504248,-0.305081,-0.526772,-0.514050,-0.735241,-0.648774,-0.585377,...,-0.653357,-0.649519,-0.486074,-0.533714,-0.414530,-0.502137,-0.503876,-0.518750,-0.440244,-0.318530
210,211,South Africa,0.332902,0.275541,0.397753,0.483857,0.378271,0.197672,0.153829,0.125427,...,-0.184171,-0.137832,-0.124875,-0.043699,0.044075,-0.101496,-0.112126,0.020065,-0.010780,0.022103
212,213,Zambia,-0.758519,-0.641859,-0.604488,-0.592440,-0.551736,-0.398109,-0.389601,-0.469498,...,-0.291441,-0.315543,-0.347683,-0.346599,-0.405702,-0.545036,-0.657134,-0.662320,-0.723668,-0.753424

In [12]:
df.to_csv('../经济/fiscal balance index.csv')

In [4]:
label = df.keys()[1:-1]

In [5]:
from sklearn.impute import KNNImputer
imputer = KNNImputer()
outputs = imputer.fit_transform(df[label].values)

In [6]:
df[label] = outputs

In [7]:
df.to_csv('tmp.csv')

In [8]:
def minToMax(datas):
    return datas.max() - datas
label = df.keys()[1:]
list = []
for value in df[label].values:
    list.append(minToMax(value))
df[label] = list

[1,
 3,
 7,
 36,
 38,
 41,
 47,
 49,
 51,
 54,
 61,
 62,
 63,
 64,
 65,
 68,
 73,
 74,
 78,
 84,
 95,
 98,
 102,
 103,
 104,
 105,
 107,
 108,
 110,
 128,
 134,
 135,
 136,
 139,
 140,
 142,
 147,
 153,
 156,
 161,
 164,
 170,
 172,
 181,
 183,
 191,
 193,
 197,
 198,
 199,
 204,
 215,
 217,
 218,
 219,
 225,
 228,
 230,
 231,
 236,
 238,
 240,
 241,
 244,
 249,
 255,
 259]

In [10]:
# 标准化
def standard(datas):
    k = np.power(np.sum(np.power(datas, 2)), 0.5)
    datas = datas / k
    return datas

In [11]:
label = df.keys()[1:]
list = []
for value in df[label].values:
    list.append(standard(value))

In [12]:
df[label] = list
df

,Country Name,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
5,Albania,0.183303,0.178569,0.188155,0.178645,0.190303,0.167353,0.165147,0.000000,0.105181,...,0.184088,0.181490,0.186876,0.187988,0.196788,0.194268,0.197768,0.196425,0.196585,0.197244
9,Argentina,0.154006,0.101951,0.010083,0.050222,0.040949,0.085191,0.085152,0.099046,0.064816,...,0.220959,0.203733,0.142687,0.123793,0.187838,0.223793,0.273216,0.266231,0.281711,0.268521
10,Armenia,0.117909,0.109424,0.000000,0.027419,0.125597,0.161812,0.162034,0.174554,0.180719,...,0.196839,0.203449,0.205895,0.196717,0.193901,0.181598,0.199647,0.220688,0.196843,0.218812
13,Australia,0.000000,0.046624,0.097598,0.064336,0.083591,0.046510,0.053148,0.046285,0.083786,...,0.226780,0.234870,0.236391,0.241261,0.250234,0.260603,0.278983,0.270452,0.269399,0.274751
14,Austria,0.058610,0.000000,0.029315,0.105590,0.073849,0.118291,0.030647,0.170694,0.124603,...,0.148462,0.134237,0.203577,0.272153,0.269541,0.239948,0.180174,0.121334,0.157737,0.204565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,"Venezuela, RB",0.297238,0.298125,0.277992,0.251428,0.241948,0.251366,0.241236,0.262685,0.256607,...,0.085175,0.050396,0.125883,0.000000,0.066221,0.029466,0.078882,0.165877,0.174675,0.199016
257,Vietnam,0.235533,0.194107,0.184491,0.161891,0.116177,0.047277,0.056788,0.000000,0.057639,...,0.099885,0.225318,0.226503,0.266563,0.261879,0.210921,0.198103,0.238563,0.259067,0.275277
261,Kosovo,0.165232,0.150238,0.059488,0.000000,0.024114,0.064865,0.088506,0.091944,0.088248,...,0.233585,0.198230,0.261753,0.243858,0.259820,0.265359,0.253080,0.258244,0.256457,0.246959
263,South Africa,0.227458,0.210365,0.189496,0.180385,0.005929,0.000000,0.031696,0.054847,0.050951,...,0.242575,0.237175,0.230094,0.223603,0.216172,0.215355,0.202590,0.197538,0.197416,0.217919
264,Zambia,0.167131,0.102089,0.066535,0.088101,0.053910,0.047612,0.107889,0.117466,0.077712,...,0.198038,0.199649,0.213534,0.233763,0.233111,0.202166,0.223130,0.233073,0.277587,0.281444

In [13]:
df.to_csv('Intentional homicides.csv')