In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('./Inflation rate.csv')
df.keys()[47:-1]

Index(['2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020'],
      dtype='object')

In [3]:
label = df.keys()[47:-1]
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
output = imputer.fit_transform(df[label])

In [4]:
df[label] = output

In [5]:
df = df.drop(df.keys()[2:47], axis=1)
df = df.drop(df.keys()[-1], axis=1)
df = df.drop(df.keys()[0], axis=1)

In [6]:
df

,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Albania,7.770526,0.484003,2.280019,2.366582,2.370728,2.932682,3.320871,2.266922,3.626047,3.429123,2.031593,1.937621,1.625865,3.501208,-0.367317,2.060598,2.028060,1.411091,1.620887
1,Argentina,5.527179,5.409608,5.531481,5.952376,5.416642,5.708397,10.271563,4.306785,4.638059,6.920339,5.745136,4.610036,4.026672,4.440454,5.452225,4.025650,3.378729,3.271391,3.107798
2,Armenia,1.060049,4.721553,6.961261,0.638928,2.892357,4.407361,8.949953,3.406767,8.176361,7.650008,2.558020,5.789668,2.981309,3.731691,-1.403608,0.969553,2.520234,1.443447,1.211436
3,Australia,2.981575,2.732596,2.343255,2.691832,3.555288,2.327611,4.350299,1.771117,2.918340,3.303850,1.762780,2.449889,2.487923,1.508367,1.276991,1.948647,1.911401,1.610768,0.846906
4,Austria,1.810358,1.355554,2.061206,2.299138,1.441549,2.168555,3.215950,0.506309,1.813534,3.286579,2.485676,2.000156,1.605812,0.896563,0.891592,2.081269,1.998380,1.530896,1.381911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"Venezuela, RB",7.751028,7.378238,10.238937,14.489961,11.513410,10.395495,16.969532,27.080941,28.187465,26.090212,21.068996,40.639428,62.168650,121.738085,254.948535,12.990858,11.686017,8.628777,5.679003
117,Vietnam,3.830828,3.234648,7.754947,8.284572,7.418017,8.344449,23.115448,6.716983,9.207466,18.677732,9.094703,6.592675,4.084554,0.631201,2.668248,3.520257,3.539628,2.795824,3.220934
118,Kosovo,2.325950,-1.084813,-1.064727,-1.385189,0.621647,4.358497,9.350418,-2.410264,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992,0.198228
119,South Africa,9.494711,5.679418,-0.692030,2.062846,3.243908,6.177807,10.074576,7.215314,4.089730,4.999267,5.724658,5.784469,6.129838,4.540642,6.571396,5.184247,4.517165,4.120246,3.210036
120,Zambia,22.233345,21.401578,17.967789,18.324440,9.019572,10.657350,12.445579,13.395255,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.732585

In [7]:
label = df.keys()[1:]
list = []
def interToMax(datas, a, b):
    M = max(a - datas.min(), datas.max() - b)
    ans = []
    for data in datas:
        if data < a:
            ans.append(1 - (a - data) / M)
        elif data > b:
            ans.append(1 - (data - b) / M)
        else:
            ans.append(1)
    return ans
for value in df[label].values:
    list.append(interToMax(value, 3, 5))
df[label] = list

In [8]:
df

,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Albania,0.177231,0.252818,0.786186,0.811892,0.813124,0.980009,1.000000,0.782296,1.000000,1.000000,0.712410,0.684503,0.591920,1.000000,0.000000,0.721024,0.711361,0.528138,0.590442
1,Argentina,0.899996,0.922299,0.899180,0.819337,0.920964,0.865619,0.000000,1.000000,1.000000,0.635717,0.858650,1.000000,1.000000,1.000000,0.914214,1.000000,1.000000,1.000000,1.000000
2,Armenia,0.559463,1.000000,0.554624,0.463832,0.975556,1.000000,0.103019,1.000000,0.278691,0.398219,0.899632,0.820677,0.995755,1.000000,0.000000,0.538913,0.891052,0.646528,0.593841
3,Australia,0.991442,0.875805,0.694976,0.856872,1.000000,0.687711,1.000000,0.429248,0.962073,1.000000,0.425376,0.744502,0.762167,0.307214,0.199752,0.511702,0.494403,0.354774,0.000000
4,Austria,0.522939,0.340557,0.623532,0.718946,0.375042,0.666581,1.000000,0.000000,0.524213,1.000000,0.793750,0.599051,0.440914,0.156497,0.154503,0.631578,0.598338,0.410872,0.351127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"Venezuela, RB",0.988994,0.990485,0.979040,0.962032,0.973941,0.978414,0.952112,0.911658,0.907231,0.915622,0.935711,0.857413,0.771278,0.532952,0.000000,0.968030,0.973250,0.985482,0.997283
117,Vietnam,1.000000,1.000000,0.847923,0.818687,0.866522,0.815381,0.000000,0.905220,0.767742,0.244969,0.773966,0.912082,1.000000,0.869239,0.981687,1.000000,1.000000,0.988729,1.000000
118,Kosovo,0.875413,0.244988,0.248701,0.189469,0.560400,1.000000,0.195895,0.000000,1.000000,0.568151,0.903283,0.772160,0.524784,0.346256,0.495989,0.720575,0.640276,0.940112,0.482138
119,South Africa,0.114269,0.866113,0.272445,0.815324,1.000000,0.767900,0.000000,0.563448,1.000000,1.000000,0.857198,0.845412,0.777353,1.000000,0.690339,0.963692,1.000000,1.000000,1.000000
120,Zambia,0.000000,0.048265,0.247518,0.226822,0.766756,0.671721,0.567955,0.512848,0.796803,0.917056,0.908555,0.885241,0.837125,0.703447,0.253208,0.908473,0.855247,0.759169,0.377220

In [9]:
# 标准化
def standard(datas):
    k = np.power(np.sum(np.power(datas, 2)), 0.5)
    datas = datas / k
    return datas
list = []
for value in df[label].values:
    list.append(standard(value))
df[label] = list

In [10]:
df

,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Albania,0.054472,0.077704,0.241634,0.249535,0.249913,0.301205,0.307350,0.240439,0.307350,0.307350,0.218959,0.210382,0.181926,0.307350,0.000000,0.221606,0.218636,0.162323,0.181472
1,Argentina,0.227029,0.232655,0.226823,0.206682,0.232318,0.218357,0.000000,0.252256,0.252256,0.160363,0.216599,0.252256,0.252256,0.252256,0.230616,0.252256,0.252256,0.252256,0.252256
2,Armenia,0.173785,0.310629,0.172282,0.144080,0.303036,0.310629,0.032001,0.310629,0.086569,0.123698,0.279452,0.254926,0.309310,0.310629,0.000000,0.167402,0.276786,0.200830,0.184464
3,Australia,0.319446,0.282187,0.223923,0.276087,0.322203,0.221582,0.322203,0.138305,0.309983,0.322203,0.137057,0.239881,0.245572,0.098985,0.064361,0.164872,0.159298,0.114309,0.000000
4,Austria,0.206138,0.134244,0.245791,0.283402,0.147838,0.262760,0.394191,0.000000,0.206640,0.394191,0.312889,0.236140,0.173804,0.061690,0.060904,0.248962,0.235859,0.161962,0.138411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"Venezuela, RB",0.251304,0.251683,0.248774,0.244453,0.247479,0.248615,0.241932,0.231653,0.230528,0.232660,0.237764,0.217869,0.195982,0.135423,0.000000,0.245977,0.247303,0.250411,0.253410
117,Vietnam,0.263509,0.263509,0.223435,0.215731,0.228336,0.214860,0.000000,0.238533,0.202307,0.064551,0.203947,0.240342,0.263509,0.229052,0.258683,0.263509,0.263509,0.260539,0.263509
118,Kosovo,0.315513,0.088298,0.089636,0.068288,0.201977,0.360416,0.070604,0.000000,0.360416,0.204771,0.325558,0.278299,0.189141,0.124796,0.178763,0.259707,0.230766,0.338832,0.173770
119,South Africa,0.031854,0.241442,0.075948,0.227283,0.278765,0.214064,0.000000,0.157070,0.278765,0.278765,0.238957,0.235671,0.216699,0.278765,0.192442,0.268643,0.278765,0.278765,0.278765
120,Zambia,0.000000,0.016693,0.085606,0.078449,0.265190,0.232321,0.196433,0.177373,0.275582,0.317172,0.314232,0.306169,0.289528,0.243294,0.087574,0.314204,0.295795,0.262566,0.130465

In [11]:
df.to_csv('New_Inflation rate.csv')